CREATE USER martin WITH PASSWORD 'password';

GRANT CONNECT ON DATABASE rehecho TO martin;

GRANT USAGE ON SCHEMA public TO martin;

GRANT SELECT, UPDATE ON TABLE Books to martin;


ALTER USER martin WITH LOGIN;
ALTER USER martin WITH CONNECTION LIMIT 5;
